/**:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 30.0
    frame_id: "base_stereo_camera"
    pixel_format: "yuyv2rgb"
    image_width: 1280 #2560
    image_height: 480 #720
    camera_name: "elp_stereo_camera"